def checkLocalRepoExistence(artifactoryUrl, localRepoName, username, password) {
  def response = sh(returnStdout: true, script: """
    curl -s -o /dev/null -w '%{http_code}' -u "${username}:${password}" -X GET "${artifactoryUrl}/api/repositories/${localRepoName}"
  """).trim()

  return response == "200"
}

def createLocalRepo(artifactoryUrl, localRepoName, repoType, packageType, username, password) {
  def createLocalRepoJson = """
  {
    "key": "${localRepoName}",
    "rclass": "${repoType}",
    "packageType": "${packageType}",
    "xrayIndex": true
  }
  """

  sh("""
    curl -u "${username}:${password}" -X PUT "${artifactoryUrl}/api/repositories/${localRepoName}" -H 'Content-Type: application/json' -d '${createLocalRepoJson}'
  """)
}

pipeline {
  agent any

  environment {
    artifactoryUrl = "https://artre.jfrog.io/artifactory"
    artifactoryCredentialsID = 'artifactory-credentials'
    SNYK_HOME = "${HOME}/bin"
    
    MAVEN_HOME = tool 'MAVEN_HOME'
    PATH = "${MAVEN_HOME}/bin:${env.PATH}"
  }
  
  stages {
    stage('Checkout') {
      steps {
        script {
          checkout([$class: 'GitSCM', 
                    branches: [[name: '*/main']], 
                    userRemoteConfigs: [[url: 'https://github.com/Artredist/spring-petclinic.git']], 
                    excludes: 'JFrog/**'])
        }
      }
    }
    
    // Mainly for debugging, but it's useful to see the Maven version
    stage('Print Environment') {
        steps {
            sh '''
            echo "MAVEN_HOME: ${MAVEN_HOME}"
            echo "PATH: ${PATH}"
            which mvn
            mvn --version
            '''
        }
    }
    
    stage('Snyk Install') {
        steps {
        // Download and install the Snyk CLI
            sh """
            curl --compressed https://static.snyk.io/cli/latest/snyk-macos -o snyk
            chmod +x ./snyk
            mkdir -p ${SNYK_HOME}
            mv ./snyk ${SNYK_HOME}/
            """
        }
    }
    
    stage('Snyk Security Scan') {
      steps {
        script {
          // Execute Snyk security scan
          def snykExitCode = sh(returnStatus: true, script: """
            export PATH="${SNYK_HOME}:${PATH}"
            snyk test --all-projects
          """)

          if (snykExitCode != 0) {
            echo "Snyk security scan failed with exit code ${snykExitCode}"
            currentBuild.result = 'UNSTABLE' // Mark the build as unstable
          }
        }
      }
    }

    stage('Create Local Repository for local-maven-fp-petclinic-pom') {
      steps {
        script {
          def repoName = 'local-maven-fp-petclinic-pom'
          def pomFilePath = "${WORKSPACE}/pom.xml"
          def repoExists
          def ARTIFACTORY_USERNAME
          def ARTIFACTORY_PASSWORD
          
          withCredentials([usernamePassword(credentialsId: artifactoryCredentialsID, passwordVariable: 'ARTIFACTORY_PASSWORD', usernameVariable: 'ARTIFACTORY_USERNAME')]) {
            ARTIFACTORY_USERNAME = env.ARTIFACTORY_USERNAME
            ARTIFACTORY_PASSWORD = env.ARTIFACTORY_PASSWORD
            repoExists = checkLocalRepoExistence(artifactoryUrl, repoName, ARTIFACTORY_USERNAME, ARTIFACTORY_PASSWORD)
          }

          // Create Artifactory local repository if it doesn't exist
          if (repoExists) {
            echo "Local repository '${repoName}' already exists."
          } else {
            createLocalRepo(artifactoryUrl, repoName, 'local', 'maven', ARTIFACTORY_USERNAME, ARTIFACTORY_PASSWORD)
            echo "Local repository '${repoName}' created successfully."
          }
          
          // Upload pom.xml to the local repository
          sh("""
            curl -u "${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}" -X PUT "${artifactoryUrl}/${repoName}/pom.xml" --upload-file "${pomFilePath}"
          """)
          
          echo "pom.xml uploaded successfully to '${repoName}' repository."
        }
      }
    }

    stage('Set Up Maven') {
        steps {
            sh '''
                export MAVEN_HOME=/opt/maven
                export PATH=$PATH:$MAVEN_HOME/bin
                mvn --version
            '''
        }
    }
    
    stage('Build with Maven') {
        steps {
            sh 'mvn clean package'
        }
    }
    
    stage('Create Local Repository for local-maven-fp-petclinic-jar') {
      steps {
        script {
          def repoName = 'local-maven-fp-petclinic-jar'
          def jarFilePath = "${WORKSPACE}/target/*.jar"
          def repoExists
          def ARTIFACTORY_USERNAME
          def ARTIFACTORY_PASSWORD
          
          withCredentials([usernamePassword(credentialsId: artifactoryCredentialsID, passwordVariable: 'ARTIFACTORY_PASSWORD', usernameVariable: 'ARTIFACTORY_USERNAME')]) {
            ARTIFACTORY_USERNAME = env.ARTIFACTORY_USERNAME
            ARTIFACTORY_PASSWORD = env.ARTIFACTORY_PASSWORD
            repoExists = checkLocalRepoExistence(artifactoryUrl, repoName, ARTIFACTORY_USERNAME, ARTIFACTORY_PASSWORD)
          }

          // Create Artifactory local repository if it doesn't exist
          if (repoExists) {
            echo "Local repository '${repoName}' already exists."
          } else {
            createLocalRepo(artifactoryUrl, repoName, 'local', 'maven', ARTIFACTORY_USERNAME, ARTIFACTORY_PASSWORD)
            echo "Local repository '${repoName}' created successfully."
          }
          
          // Upload JAR to the local repository
            sh("""
              find ${WORKSPACE}/target -name '*.jar' | while read jarFile; do
                curl -u "${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}" -X PUT "${artifactoryUrl}/${repoName}/" --upload-file "\$jarFile"
              done
            """)


          echo "JAR uploaded successfully to '${repoName}' repository."
        }
      }
    }

    stage('Build and Push Docker Image') {
        steps {
            script {
              def dockerhubCredentials = withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                return [
                  username: DOCKER_USERNAME,
                  password: DOCKER_PASSWORD
                ]
              }
    
              def dockerhubUsername = dockerhubCredentials.username
              def dockerhubPassword = dockerhubCredentials.password
    
              // Log in to DockerHub
              sh "echo '${dockerhubPassword}' | docker login -u '${dockerhubUsername}' --password-stdin"
    
              // Build the Docker image
              sh './mvnw spring-boot:build-image'
    
              // Tag the built image with DockerHub repository name
              def dockerhubRepo = 'artredist/petclinic-fp'
              def dockerhubImage = "${dockerhubRepo}:3.1.0-SNAPSHOT"
              sh "docker tag docker.io/library/spring-petclinic:3.1.0-SNAPSHOT ${dockerhubImage}"
    
              // Push the tagged image to DockerHub
              sh "docker push ${dockerhubImage}"
            }
        }
    }
  }
}
